version: '3.4'

services:
  db:
    image: mysql:latest
    container_name: my-sql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"

